module.exports = {
  // App Settings
  MONGO_URI: process.env.MONGO_URI || 'mongodb://beestalk:selim123@ds047484.mongolab.com:47484/heroku_3zk1bm97',
  TOKEN_SECRET: process.env.TOKEN_SECRET || 'sfyIsTheBestNoOneElse:)',

  // OAuth 2.0
  GITHUB_SECRET: process.env.GITHUB_SECRET || 'YOUR_GITHUB_CLIENT_SECRET',
  LINKEDIN_SECRET: process.env.LINKEDIN_SECRET || 'YOUR_LINKEDIN_CLIENT_SECRET',
  TWITCH_SECRET: process.env.TWITCH_SECRET || 'YOUR_TWITCH_CLIENT_SECRET',
  WINDOWS_LIVE_SECRET: process.env.WINDOWS_LIVE_SECRET || 'YOUR_MICROSOFT_CLIENT_SECRET',
  YAHOO_SECRET: process.env.YAHOO_SECRET || 'YOUR_YAHOO_CLIENT_SECRET',
  BITBUCKET_SECRET: process.env.YAHOO_SECRET || 'YOUR_BITBUCKET_CLIENT_SECRET',


  GOOGLE_SECRET: process.env.GOOGLE_SECRET || '1Hc9KH1uD0RQKayEP-q61fHm',
  FACEBOOK_SECRET: process.env.FACEBOOK_SECRET || 'b5c3e851c18469abde7cf74b0ce97014',
  FOURSQUARE_SECRET: process.env.FOURSQUARE_SECRET || 'HJMLERRNU2K5GXDJGTUUXFAQFOE0UF41FCNMGOJTR3BQFHUQ',
  INSTAGRAM_SECRET: process.env.INSTAGRAM_SECRET || '92e4e676ef3c40d4897bbf86b3792fee',

  // OAuth 1.0
  TWITTER_KEY: process.env.TWITTER_KEY || '76NlosqwiydSqaTTwoi9YjEB0',
  TWITTER_SECRET: process.env.TWITTER_SECRET || 'SeYAPPoWdoG1GANqp6LS8wQNeqwjozsDhgteXs7Enc2KFDTvBo'
};
